version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    # network_mode: host
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - 9090:9090
    restart: always
    user: root
    volumes:
      - ./prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    # network_mode: host
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    # network_mode: host
    restart: unless-stopped
    ports:
      - 9100:9100
  
