{
 "title": "Whisper APM",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "avg http_request_size(Mb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_size_bytes_sum{job=\"whisper-api\",my_handler=\"/audio-asr\"}[5m])/ rate(http_request_size_bytes_count{job=\"whisper-api\",my_handler=\"/audio-asr\"}[5m])/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "avg http_request_size(kb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_response_size_bytes_sum{job=\"whisper-api\", my_handler=\"/audio-asr\"} [5m])/rate(http_response_size_bytes_count{job=\"whisper-api\", my_handler=\"/audio-asr\"} [5m])/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_requests per sec (200 code)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total {job=\"whisper-api\", my_handler=\"/audio-asr\", my_status=\"2xx\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_requests per sec (no 2xx)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{my_handler=\"/audio-asr\",my_method=\"POST\",my_status!=\"2xx\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_requests error rate(%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{my_handler=\"/audio-asr\",my_method=\"POST\",my_status!=\"2xx\"}[5m])/rate(http_requests_total{my_handler=\"/audio-asr\",my_method=\"POST\",my_status=\"2xx\"}[5m])*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_requests_inprogress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "http_requests_inprogress{job=\"whisper-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_request_duration_seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"whisper-api\",my_handler=\"/audio-asr\",my_status=\"2xx\"}[5m])/rate(http_request_duration_seconds_count{job=\"whisper-api\",my_handler=\"/audio-asr\",my_status=\"2xx\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_request_duration_seconds_bucket-whisper1",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_bucket{job=\"whisper-api\",my_handler=\"/audio-asr\",instance=\"whisper1-eqix-sv5:9000\"}[5m])",
     "legendFormat": "{{ie}}"
    }
   ]
  },
  {
   "title": "http_request_duration_seconds_bucket-whisper2",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_bucket{job=\"whisper-api\",my_handler=\"/audio-asr\",instance=\"whisper2-eqix-sv5:9000\"}[5m])",
     "legendFormat": "{{ie}}"
    }
   ]
  },
  {
   "title": "95% quantile http_request_duration_seconds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job=\"whisper-api\",my_handler=\"/audio-asr\",my_status=\"2xx\"}[5m]))",
     "legendFormat": "{{ie}}"
    }
   ]
  },
  {
   "title": "90% quantile http_request_duration_seconds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(http_request_duration_seconds_bucket{job=\"whisper-api\",my_handler=\"/audio-asr\",my_status=\"2xx\"}[5m]))",
     "legendFormat": "{{ie}}"
    }
   ]
  },
  {
   "title": "60% quantile http_request_duration_seconds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.60, rate(http_request_duration_seconds_bucket{job=\"whisper-api\",my_handler=\"/audio-asr\",my_status=\"2xx\"}[5m]))",
     "legendFormat": "{{ie}}"
    }
   ]
  }
 ]
}